version: '3.7'
services:

  discovery-service:
    image: moratello/discovery-service:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always
    networks:
      - rsa-network
      
  api-gateway:
    image: moratello/gatewayservice:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    restart: always
    depends_on:
      - discovery-service
    networks:
      - rsa-network

  couchdb-service:
    image: moratello/couchdb:0.0.1-SNAPSHOT   
    restart: always
    scale: 2
    depends_on:
      - discovery-service
    networks:
      - rsa-network

  rsa-service:
    image: moratello/rsa-decryption:0.0.1-SNAPSHOT   
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - discovery-service
    networks:
      - rsa-network
  
# Networks to be created to facilitate communication between containers
networks:
  rsa-network:
